insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('im62', 'Einti', '58 Annamark Court');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('fc33', 'Livepath', '346 Hoard Court');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('fc29', 'Skippad', '06840 Park Meadow Circle');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('cn52', 'Bluezoom', '79 Morningstar Street');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('um33', 'Avamba', '86299 Debra Park');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('ve61', 'Livetube', '435 Rockefeller Terrace');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('wz57', 'Katz', '18782 Mccormick Pass');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('ik10', 'Pixope', '55 Declaration Trail');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('tj44', 'Thoughtbeat', '314 Roth Center');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('xd86', 'Dazzlesphere', '081 Stone Corner Pass');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('ym34', 'DabZ', '5 Utah Crossing');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('xe42', 'Devify', '07 Trailsway Circle');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('aj71', 'Voomm', '0570 Everett Road');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('hk32', 'Topicstorm', '7 Ilene Hill');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('pa72', 'Jetwire', '25 Sheridan Plaza');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('pq00', 'Eayo', '653 Eggendart Alley');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('pb19', 'Livetube', '2 Little Fleur Park');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('mr45', 'Teklist', '49507 Ronald Regan Center');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('ky33', 'Twitterbeat', '66026 Fairfield Alley');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('pk27', 'Gigashots', '4 Ronald Regan Crossing');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('tx19', 'Layo', '0040 Caliangt Road');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('nr29', 'Devcast', '2 Carey Junction');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('ke05', 'Tagchat', '36242 Ronald Regan Road');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('wu88', 'Ozu', '0384 Upham Hill');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('dz27', 'Riffpath', '19 Harper Terrace');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('ox32', 'Trunyx', '003 Susan Terrace');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('nf68', 'Gigashots', '9798 Main Avenue');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('pe47', 'Skinte', '96 Maywood Terrace');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('ev51', 'Gigaclub', '3651 David Point');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('qf45', 'Livetube', '977 Hoffman Park');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('nr21', 'Vinder', '4 Corscot Trail');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('iq05', 'Jayo', '0 Mayer Point');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('ym71', 'Eazzy', '04449 Main Court');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('dj63', 'Shufflester', '0 Orin Center');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('pk55', 'Dynava', '6 Stang Road');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('gy91', 'Voonyx', '77 Hanson Court');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('ts23', 'Cogibox', '3018 Anderson Drive');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('mh40', 'Skidoo', '43 Charing Cross Crossing');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('xk67', 'Topicshots', '2577 Porter Drive');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('nm79', 'Roombo', '91271 Chive Junction');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('ot26', 'Eire', '71 Delaware Place');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('um42', 'Devpoint', '02891 Muir Parkway');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('wy41', 'BlogXS', '98 Manitowish Road');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('yg01', 'Dabjam', '59731 Sunbrook Trail');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('vb09', 'Mymm', '9 Manitowish Parkway');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('ew89', 'Ntags', '70850 Scofield Pass');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('yf86', 'Buzzdog', '1914 Memorial Crossing');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('as29', 'Livetube', '5173 Grim Court');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('qg37', 'Zava', '32830 Bunting Park');
insert into HevlelGazar (hevlelGazarId, hevlelGazarNer, hevlelGazarLocation) values ('xs86', 'Janyx', '9268 Roxbury Pass');